# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('vmnet', 'Network of VMs')], max_length=20)),
            ],
        ),
    ]
