# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedIPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(protocol='ipv4')),
                ('user_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.UserToken')),
            ],
        ),
    ]
