# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedipaddress',
            name='ip_address',
            field=models.GenericIPAddressField(protocol='ipv4', unique=True),
        ),
    ]
