# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0002_auto_20151218_2349'),
        ('resources', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveVMResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_time', models.DateTimeField()),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Network')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Resource')),
                ('user_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.UserToken')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backing_image', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='VMTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('memory', models.IntegerField()),
                ('image_fingerprint', models.CharField(max_length=64)),
                ('order_id', models.IntegerField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Resource')),
            ],
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vm.VMTemplate'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='vm_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vm.ActiveVMResource'),
        ),
        migrations.AlterUniqueTogether(
            name='activevmresource',
            unique_together=set([('resource', 'user_token')]),
        ),
    ]
