# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activevmresource',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
