# Generated by Django 2.0.5 on 2018-05-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0002_activevmresource_is_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmtemplate',
            name='boot_type',
            field=models.CharField(default='efi', max_length=8),
        ),
    ]
