# Generated by Django 2.0.5 on 2018-05-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0003_vmtemplate_boot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmtemplate',
            name='boot_type',
            field=models.CharField(choices=[('efi', 'EFI boot'), ('mbr', 'MBR boot')], default='efi', max_length=8),
        ),
    ]
