# Generated by Django 2.2 on 2019-06-06 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0004_auto_20180524_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmtemplate',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.Resource'),
        ),
    ]
