# Generated by Django 4.2.1 on 2023-05-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0005_auto_20190606_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activevmresource',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vmtemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
