# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import insektavm.network.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', insektavm.network.models.IPv4NetworkField(max_length=18)),
                ('in_use', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('network', insektavm.network.models.IPv4NetworkField(max_length=18)),
                ('subnet_prefix', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='network',
            name='range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subnet', to='network.NetworkRange'),
        ),
    ]
