# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 23:49
from __future__ import unicode_literals

from django.db import migrations
import insektavm.network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='network',
            field=insektavm.network.models.IPv4NetworkField(),
        ),
        migrations.AlterField(
            model_name='networkrange',
            name='network',
            field=insektavm.network.models.IPv4NetworkField(),
        ),
    ]
